import { Theme } from "../constants.slint";
import { IconButton } from "../common/icon_button.slint";

export component NavButtons inherits VerticalLayout {
    alignment: center;
    padding-right: Theme.spacingXs;

    HorizontalLayout {
        spacing: Theme.spacingXs;
        IconButton {
            icon_source: @image-url("../icons/nav_button.svg");
            icon_width: Theme.spacingSm;
            icon_height: Theme.iconSizeMd;
        }

        IconButton {
            icon_source: @image-url("../icons/nav_button.svg");
            icon_width: Theme.spacingSm;
            icon_height: Theme.iconSizeMd;
            icon_rotation: 180deg;
        }
    }
}
