import { Theme } from "../constants.slint";

export component SearchBar inherits Rectangle {
    in-out property <string> text;
    in property <color> custom-background: Theme.secondary;
    in property <string> placeholder-text: @tr("Search...");
    callback accepted(string);
    callback edited(string);

    height: Theme.searchBarHeight;
    background: root.custom-background;
    border-radius: Theme.searchBarHeight / 2;
    border-width: Theme.borderWidth;
    border-color: Theme.divider; // Divider
    forward-focus: input;

    HorizontalLayout {
        padding-left: Theme.paddingMd;
        padding-right: Theme.paddingMd;
        spacing: Theme.spacingSm;

        VerticalLayout {
            alignment: center;

            // search icon
            Image {
                width: Theme.iconSizeMd;
                height: Theme.iconSizeMd;
                source: @image-url("../icons/search.svg");
                colorize: Theme.accent; // Text Secondary
            }
        }

        // Custom text field / placeholder
        Rectangle {
            horizontal-stretch: 1;
            clip: true;

            // Placeholder text (visible when empty)
            if (input.text == ""): Text {
                text: root.placeholder-text;
                color: Theme.textSecondary; // Text Secondary
                font-size: Theme.subtitle;
                vertical-alignment: center;
                overflow: elide;
                x: 0px;
            }

            input := TextInput {
                property <length> computed_x;

                x: Math.min(0px, Math.max(parent.width - self.width - self.text-cursor-width, self.computed_x));
                width: Math.max(parent.width - self.text-cursor-width, self.preferred-width);
                height: 100%;
                text <=> root.text;
                color: Theme.textPrimary; // Text Primary
                font-size: Theme.subtitle;
                vertical-alignment: center;
                single-line: true;

                cursor-position-changed(cursor-position) => {
                    if cursor-position.x + self.computed_x < 0px {
                        self.computed_x = - cursor-position.x;
                    } else if cursor-position.x + self.computed_x > parent.width - self.text-cursor-width {
                        self.computed_x = parent.width - cursor-position.x - self.text-cursor-width;
                    }
                }

                accepted => {
                    root.accepted(self.text);
                }
                edited => {
                    root.edited(self.text);
                }
            }
        }
    }
}
