import { NavButtons } from "nav_buttons.slint";
import { SearchBar } from "search_bar.slint";
import { Theme, Pages } from "../constants.slint";
import { IconButton } from "../common/icon_button.slint";
import { AccountsPopup } from "../common/accounts_popup.slint";
import { AppCallbacks } from "../callbacks.slint";
import { AppProps } from "../props.slint";
import { SettingsState } from "../settings/settings.slint";
import { SearchPageProps } from "../main_content/search.slint";

export global TopBarProps {
    in-out property <bool> can_go_back: false;
    in-out property <bool> can_go_forward: false;
}

export component TopBar inherits Rectangle {
    height: Theme.topbarHeight;
    background: Theme.primary; // Sampled Topbar Background

    // Bottom border for the top bar
    Rectangle {
        y: parent.height - Theme.borderWidth;
        height: Theme.borderWidth;
        background: Theme.divider;
    }

    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            padding-left: Theme.paddingLg;
            padding-right: Theme.paddingLg;

            HorizontalLayout {
                horizontal-stretch: 1;

                NavButtons {
                    can_go_back: TopBarProps.can_go_back;
                    can_go_forward: TopBarProps.can_go_forward;
                    go_back => {
                        AppCallbacks.navigate_back();
                    }
                    go_forward => {
                        AppCallbacks.navigate_forward();
                    }
                }

                HorizontalLayout {
                    horizontal-stretch: 1;
                    alignment: stretch;
                    padding-right: Theme.paddingLg;
                    padding-left: Theme.paddingLg;
                    SearchBar {
                        horizontal-stretch: 1;
                        accepted(txt) => {
                            SearchPageProps.search_query = txt;
                            AppProps.active_page = Pages.Search;
                        }
                    }
                }
            }

            HorizontalLayout {
                horizontal-stretch: 0;
                spacing: Theme.spacingLg;

                // Profile Action
                Rectangle {
                    width: Theme.topbarIconSize;
                    height: Theme.topbarIconSize;

                    IconButton {
                        accessible-label: @tr("Accounts");
                        icon_source: @image-url("../icons/profile.svg");
                        icon_size: Theme.iconSizeLg;
                        clicked => {
                            accounts_popup.show();
                        }
                    }

                    accounts_popup := AccountsPopup {
                        x: -180px;
                        y: parent.height + 6px;
                    }
                }

                // Settings Action
                IconButton {
                    icon_source: @image-url("../icons/settings.svg");
                    icon_size: Theme.iconSizeLg;
                    clicked => {
                        SettingsState.show_settings = true;
                    }
                }
            }
        }
    }
}
