import { NavButtons } from "nav_buttons.slint";
import { SearchBar } from "search_bar.slint";
import { Theme } from "../constants.slint";
import { IconButton } from "../common/icon_button.slint";

export component TopBar inherits Rectangle {
    callback settings_clicked();
    callback search-submitted(string);

    height: Theme.topbarHeight;
    background: Theme.primary; // Sampleed Topbar Background

    // Bottom border for the top bar
    Rectangle {
        y: parent.height - Theme.borderWidth;
        height: Theme.borderWidth;
        background: Theme.divider;
    }

    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            padding-left: Theme.paddingLg;
            padding-right: Theme.paddingLg;

            HorizontalLayout {
                horizontal-stretch: 1;

                NavButtons { }

                HorizontalLayout {
                    horizontal-stretch: 1;
                    alignment: stretch;
                    padding-right: Theme.paddingLg;
                    padding-left: Theme.paddingLg;
                    SearchBar {
                        horizontal-stretch: 1;
                        accepted(txt) => {
                            root.search-submitted(txt);
                        }
                    }
                }
            }

            HorizontalLayout {
                horizontal-stretch: 0;
                spacing: Theme.spacingLg;

                // Profile Action
                IconButton {
                    icon_source: @image-url("../icons/profile.svg");
                    icon_size: Theme.iconSizeLg;
                }

                // Settings Action
                IconButton {
                    icon_source: @image-url("../icons/settings.svg");
                    icon_size: Theme.iconSizeLg;
                    clicked => {
                        root.settings_clicked();
                    }
                }
            }
        }
    }
}
