import { Pages } from "constants.slint";
import { SongModel } from "./types/song_view.slint";

export global AppCallbacks {
    callback search-clicked(string);
    callback resize();
    callback active-page-changed(Pages);
    pure callback play-song(SongModel);
    pure callback add-song-to-queue(SongModel);
}

export global BottomBarCallbacks {
    callback play-pause-clicked();
    callback toggle-repeat();
    callback next-song();
    callback prev-song();
    callback shuffle();
    callback set-volume(int);
}
