import { SongModel, LyricLineModel } from "types/song_view.slint";
import { Constants, Pages } from "constants.slint";
import { AppCallbacks } from "callbacks.slint";

export global PlayerProps {
    in-out property <SongModel> current_song: Constants.defaultSong;
    in-out property <int> repeat_mode: 0;
    in-out property <bool> playing: false;
    in-out property <int> current_duration: 0;
    in-out property <string> current_pos_str: "00:00";
}

export global AppProps {
    in-out property <Pages> active_page: Pages.AllSongs;

    changed active_page => {
        AppCallbacks.active_page_changed(self.active_page);
    }
}

export global QueuePageProps {
    in-out property <[SongModel]> queue: Constants.testSongs;
    in-out property <image> blurred-cover;
    in-out property <bool> show_queue: false;
    in-out property <bool> show_lyrics: false;
    in-out property <bool> lyrics_loading: false;
    in-out property <bool> has_lyrics: false;
    in-out property <bool> is_synced: false;
    in-out property <[LyricLineModel]> lyrics_lines: [];

    changed show_queue => {
        AppCallbacks.queue-toggled(self.show_queue);
    }
}
