exports_files([
    "0001-Fix-pkgconfig_build.bzl-for-Windows-build-with-Bzlmod.patch",
    "tauri_macros.patch",
    "rules_rust_prost_rust_deps.patch",
    "rules_flutter_sandbox.patch",
    "khronos_api.patch",
    "rules_rust_gnu_windows.patch",
])
