crates = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate", isolate = True)
crates.from_cargo(
    name = "crates",
    cargo_lockfile = "//:Cargo.lock",
    lockfile = "//:crates.lock",
    manifests = ["//:Cargo.toml"],
    supported_platform_triples = [
        "x86_64-unknown-linux-gnu",
        "aarch64-unknown-linux-gnu",
        "x86_64-pc-windows-msvc",
        "x86_64-pc-windows-gnu",
        "x86_64-apple-darwin",
        "aarch64-apple-darwin",
        "x86_64-linux-android",
        "aarch64-linux-android",
    ],
)
crates.annotation(
    crate = "protoc-gen-prost",
    gen_binaries = ["protoc-gen-prost"],
)
crates.annotation(
    crate = "slint-lsp",
    gen_binaries = ["slint-lsp"],
)
crates.annotation(
    build_script_data = ["@@//external/ffmpeg:gen_dir"],
    build_script_env = {
        "FFMPEG_INCLUDE_DIR": "$(execpath @@//external/ffmpeg:gen_dir)/include",
        "FFMPEG_LIBS_DIR": "$(execpath @@//external/ffmpeg:gen_dir)/lib",
        "FFMPEG_LINK_MODE": "static",
    },
    build_script_rustc_env = {
        "FFMPEG_LINK_MODE": "static",
    },
    crate = "rusty_ffmpeg",
)
crates.annotation_select(
    build_script_data = [
        "@@//:ndk_sysroot",
    ],
    build_script_env = {
        "BINDGEN_EXTRA_CLANG_ARGS": "--target=aarch64-linux-android --sysroot=$${pwd}/external/rules_android_ndk++android_ndk_repository_extension+androidndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -D__float128=double -D__ssize_t=long -D__intptr_t=long",
    },
    crate = "rusty_ffmpeg",
    triples = ["aarch64-linux-android"],
)
crates.annotation_select(
    build_script_data = [
        "@@//:ndk_sysroot",
    ],
    build_script_env = {
        "BINDGEN_EXTRA_CLANG_ARGS": "--target=x86_64-linux-android --sysroot=$${pwd}/external/rules_android_ndk++android_ndk_repository_extension+androidndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -D__float128=double -D__ssize_t=long -D__intptr_t=long",
    },
    crate = "rusty_ffmpeg",
    triples = ["x86_64-linux-android"],
)
crates.annotation_select(
    build_script_data = [
        "@@//:mingw_sysroot",
    ],
    build_script_env = {
        "BINDGEN_EXTRA_CLANG_ARGS": "--target=x86_64-pc-windows-gnu --sysroot=$${pwd}/external/+_repo_rules2+mingw_compiler_files/x86_64-w64-mingw32 -D__float128=double -D__ssize_t=long -D__intptr_t=long",
    },
    crate = "rusty_ffmpeg",
    triples = ["x86_64-pc-windows-gnu"],
)
crates.annotation_select(
    crate = "rusty_ffmpeg",
    triples = [
        "x86_64-unknown-linux-gnu",
        "aarch64-unknown-linux-gnu",
        "x86_64-linux-android",
        "aarch64-linux-android",
    ],
)
crates.annotation_select(
    crate = "windows_x86_64_gnu",
    triples = ["x86_64-pc-windows-gnu"],
    version = "0.42.2",
    deps = ["@@//:libwindows_0_42_2"],
)
crates.annotation_select(
    crate = "windows_x86_64_gnu",
    triples = ["x86_64-pc-windows-gnu"],
    version = "0.52.6",
    deps = ["@@//:libwindows_0_52_0"],
)
crates.annotation_select(
    crate = "windows_x86_64_gnu",
    triples = ["x86_64-pc-windows-gnu"],
    version = "0.53.1",
    deps = ["@@//:libwindows_0_53_0"],
)
crates.annotation_select(
    crate = "winapi-x86_64-pc-windows-gnu",
    triples = ["x86_64-pc-windows-gnu"],
    version = "0.4.0",
    deps = ["@@//:libwinapi_all"],
)
crates.annotation(
    compile_data_glob = [
        "**/*.xml",
        "**/*.idl",
    ],
    crate = "khronos_api",
    patch_args = ["-p1"],
    patches = ["//patches:khronos_api.patch"],
)
crates.annotation(
    build_script_env = {
        "CARGO_PKG_AUTHORS": "",
        "CARGO_PKG_NAME": "",
        "CARGO_PKG_DESCRIPTION": "",
        "CARGO_PKG_REPOSITORY": "",
        "CARGO_PKG_HOMEPAGE": "",
        "CARGO_PKG_LICENSE": "",
    },
    crate = "rav1e",
)
crates.annotation(
    build_script_data = [
        "@@//external/openssl:gen_dir",
    ],
    build_script_env = {
        "OPENSSL_NO_VENDOR": "1",
        "OPENSSL_LIB_DIR": "$(execpath @@//external/openssl:gen_dir)/lib",
        "OPENSSL_INCLUDE_DIR": "$(execpath @@//external/openssl:gen_dir)/include",
        "OPENSSL_STATIC": "1",
    },
    crate = "openssl-sys",
)
use_repo(
    crates,
    "crates",
    "crates__winapi-x86_64-pc-windows-gnu-0.4.0",
    "crates__windows_x86_64_gnu-0.42.2",
    "crates__windows_x86_64_gnu-0.52.6",
    "crates__windows_x86_64_gnu-0.53.1",
)

bindeps = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
bindeps.spec(
    artifact = "bin",
    package = "slint-tr-extractor",
    version = "1.17.1",
)
bindeps.annotation(
    crate = "slint-tr-extractor",
    gen_all_binaries = True,
)
bindeps.from_specs(
    name = "bindeps",
    host_tools = "@rust_host_tools_nightly",
)
use_repo(bindeps, "bindeps")
