module(
    name = "moosync",
    version = "11.0.2",
)

bazel_dep(name = "rules_rust", version = "0.70.0")
single_version_override(
    module_name = "rules_rust",
    patch_strip = 1,
    patches = ["//patches:rules_rust_gnu_windows.patch"],
)

bazel_dep(name = "rules_rust_prost", version = "0.68.1")
bazel_dep(name = "protobuf", version = "33.2", repo_name = "com_google_protobuf")
bazel_dep(name = "rules_proto", version = "7.1.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")
bazel_dep(name = "rules_perl", version = "0.5.0")
bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "nasm", version = "2.16.03.bcr.2")
bazel_dep(name = "rules_cc", version = "0.2.16")
bazel_dep(name = "rules_android", version = "0.7.2")
bazel_dep(name = "rules_kotlin", version = "2.3.20")
bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "rules_appimage", version = "1.19.0")
bazel_dep(name = "bazel_env.bzl", version = "0.5.0")
bazel_dep(name = "aspect_bazel_lib", version = "2.22.5")
bazel_dep(name = "rules_shell", version = "0.8.0")
bazel_dep(name = "rpmpack", version = "0.6.0")
git_override(
    module_name = "rpmpack",
    commit = "2467806670a618497006ff8d8623b0430c7605a9",
    remote = "https://github.com/google/rpmpack.git",
)

include("//modules:external_deps.MODULE.bazel")

include("//modules:rust_toolchains.MODULE.bazel")

include("//modules:crates.MODULE.bazel")

include("//modules:android_toolchains.MODULE.bazel")

register_toolchains(
    "//:shell_android_x86_64_toolchain",
    "//:shell_android_arm64_toolchain",
)

sh_configure = use_extension("@rules_shell//shell/private/extensions:sh_configure.bzl", "sh_configure")
use_repo(sh_configure, "local_config_shell")
