name: moosync
base: core22
version: "11.0.2"
summary: Customizable music player
description: |
  Moosync is a simple music player with a primary goal to provide a clean and easy interface.
  Through Moosync you can easily listen songs from your desktop or through Youtube and Spotify.
  Some of its features include:
    - Play audio files on your desktop.
    - Seamlessly integrate your Spotify and Youtube playlists.
    - Add Spotify and Youtube tracks and playlists by URLs.
    - Play songs directly from youtube using youtube embed.
    - Scrobble your tracks on LastFM.
    - Get music recommendations directly from Spotify, Youtube and LastFM
    - Mix and match songs from different providers in a single playlist
    - Easy to use interface
    - Customizable theme engine
    - Develop own apps on top of Moosync Extension API
    - Available on Windows and Linux and MacOS

grade: stable
confinement: strict

architectures:
  - amd64

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  moosync:
    command: usr/bin/moosync
    desktop: usr/share/applications/moosync.desktop
    extensions: [gnome]
    plugs:
      - network
      - audio-playback
      - dbus
      - mpris
      - home

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  moosync:
    plugin: rust
    source: https://github.com/Moosync/Moosync.git
    build-packages:
      - curl
      - build-essential
      - libssl-dev
      - libwebkit2gtk-4.1-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - patchelf
      - alsa-tools
      - libasound2-dev
      - libudev-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - gstreamer1.0-tools
      - gstreamer1.0-x
      - gstreamer1.0-alsa
      - gstreamer1.0-gl
      - gstreamer1.0-gtk3
      - gstreamer1.0-qt5
      - gstreamer1.0-pulseaudio
      - file
      - libfuse2
      - xdg-utils
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
      - libasound2
      - libgtk-3-0
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-bad1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - gstreamer1.0-tools
      - gstreamer1.0-x
      - gstreamer1.0-alsa
      - gstreamer1.0-gl
      - gstreamer1.0-gtk3
      - gstreamer1.0-qt5
      - gstreamer1.0-pulseaudio
      - librsvg2-2
      - libunwind8
      - libudev1
      - libssl3
      - libappindicator3-1
      - libfuse2
      - xdg-utils
    override-build: |
      set -eux
      rustup target add wasm32-unknown-unknown
      rustup target add $(rustc -vV | grep "host:" | awk '{print $2}')
      cargo install tauri-cli --locked
      cargo install trunk --locked
      cargo tauri build --no-bundle

      # Install the built binary
      install -Dm755 target/release/moosync $SNAPCRAFT_PART_INSTALL/usr/bin/moosync

      # Copy all icons from src-tauri/icons to hicolor
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor
      cp -r src-tauri/icons/* $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/

      # Copy all .desktop files
      find . -name '*.desktop' -exec install -Dm644 {} $SNAPCRAFT_PART_INSTALL/usr/share/applications/ \;

      snapcraftctl build
