export struct ContextSubMenuItem {
    action_id: string,
    title: string,
    icon: image,
}

export struct ContextMenuItem {
    action_id: string,
    title: string,
    icon: image,
    has_sub_menu: bool,
    sub_items: [ContextSubMenuItem],
}

export global ContextMenuItems {
    pure public function get_all_songs_items() -> [ContextMenuItem] {
        return [
            {
                action_id: "play_now",
                title: @tr("Play Now"),
                icon: @image-url("../icons/play.svg"),
                has_sub_menu: false,
                sub_items: [],
            },
            {
                action_id: "play_next",
                title: @tr("Play Next"),
                icon: @image-url(""),
                has_sub_menu: false,
                sub_items: [],
            },
            {
                action_id: "clear_queue_and_play",
                title: @tr("Clear queue and play"),
                icon: @image-url(""),
                has_sub_menu: false,
                sub_items: [],
            },
            {
                action_id: "add_to_queue",
                title: @tr("Add to Queue"),
                icon: @image-url("../icons/add_to_queue.svg"),
                has_sub_menu: false,
                sub_items: [],
            },
        ];
    }

    pure public function get_queue_items() -> [ContextMenuItem] {
        return [
            {
                action_id: "play_now",
                title: @tr("Play Now"),
                icon: @image-url("../icons/play.svg"),
                has_sub_menu: false,
                sub_items: [],
            },
            {
                action_id: "remove_from_queue",
                title: @tr("Remove from Queue"),
                icon: @image-url(""),
                has_sub_menu: false,
                sub_items: [],
            },
        ];
    }

    pure public function get_playlist_song_items() -> [ContextMenuItem] {
        return [
            {
                action_id: "play_now",
                title: @tr("Play Now"),
                icon: @image-url("../icons/play.svg"),
                has_sub_menu: false,
                sub_items: [],
            },
            {
                action_id: "play_next",
                title: @tr("Play Next"),
                icon: @image-url(""),
                has_sub_menu: false,
                sub_items: [],
            },
            {
                action_id: "clear_queue_and_play",
                title: @tr("Clear queue and play"),
                icon: @image-url(""),
                has_sub_menu: false,
                sub_items: [],
            },
            {
                action_id: "add_to_queue",
                title: @tr("Add to Queue"),
                icon: @image-url("../icons/add_to_queue.svg"),
                has_sub_menu: false,
                sub_items: [],
            },
            {
                action_id: "remove_from_playlist",
                title: @tr("Remove from Playlist"),
                icon: @image-url(""),
                has_sub_menu: false,
                sub_items: [],
            },
        ];
    }

    pure public function get_playlists_items() -> [ContextMenuItem] {
        return [
            {
                action_id: "delete_playlist",
                title: @tr("Delete Playlist"),
                icon: @image-url(""),
                has_sub_menu: false,
                sub_items: [],
            },
            {
                action_id: "export_playlist",
                title: @tr("Export Playlist"),
                icon: @image-url(""),
                has_sub_menu: false,
                sub_items: [],
            },
            {
                action_id: "save_playlist",
                title: @tr("Save Playlist"),
                icon: @image-url(""),
                has_sub_menu: false,
                sub_items: [],
            },
        ];
    }

    pure public function get_add_to_playlist_title() -> string {
        return @tr("Add to Playlist");
    }

    pure public function get_goto_album_title(album_title: string) -> string {
        return @tr("Go to album") + " (" + album_title + ")";
    }

    pure public function get_goto_artists_title() -> string {
        return @tr("Go to artists");
    }

    pure public function get_remove_from_playlist_title() -> string {
        return @tr("Remove from Playlist");
    }
}
