export struct AlbumModel {
    id: string,
    title: string,
    songs_count: int,
    coverPath: image,
    coverPathUrl: string,
}

export struct PlaylistModel {
    id: string,
    title: string,
    songs_count: int,
    coverPath: image,
    coverPathUrl: string,
}

export struct ArtistModel {
    id: string,
    mbid: string,
    title: string,
    songs_count: int,
    coverPath: image,
    coverPathUrl: string,
    sanitized_name: string,
}

export struct GenreModel {
    id: string,
    title: string,
    songs_count: int,
    coverPath: image,
    coverPathUrl: string,
}


export struct SongModel {
    // InnerSong fields
    id: string,
    path: string,
    size: float,
    inode: string,
    deviceno: string,
    title: string,
    date: string,
    year: string,
    lyrics: string,
    release_type: string,
    bitrate: float,
    codec: string,
    container: string,
    duration_s: int,
    sample_rate: float,
    hash: string,
    type: int,
    url: string,
    song_cover_path_high: string,
    playback_url: string,
    song_cover_path_low: string,
    date_added: int,
    provider_extension: string,
    icon: string,
    show_in_library: bool,
    track_no: float,
    library_item: bool,
    album_id: string,
    album_name: string,
    album_artist: string,
    album_coverpath_high: string,
    album_coverpath_low: string,
    album_song_count: float,
    album_year: string,
    artists: [ArtistModel],
    genre: [GenreModel],
    coverPathHigh: image,
    coverPathLow: image,
    coverPathUrlHigh: string,
    coverPathUrlLow: string,
    extensionIcon: image,
    duration_str: string,
}

export global CoverHelper {
    pure callback fetch_cover_high(SongModel) -> image;
}

export struct SearchResult {
    songs: [SongModel],
    albums: [AlbumModel],
    artists: [ArtistModel],
    playlists: [PlaylistModel],
    genres: [GenreModel],
}
