// Automatically generated by flapigen
package services.players.librespot;


public interface LibrespotCallbacks {


    void onPlay();


    void onStop();


    void onPause();


    void onTimeChange(long pos);


    void onEnded();


    void onSeek(long pos);


    void onConnected();

}
