// Automatically generated by flapigen
package services.players.librespot;
import androidx.annotation.NonNull;

public final class LibrespotWrapper {

    public LibrespotWrapper(@NonNull LibrespotCallbacks callbacks) {
        mNativeObj = init(callbacks);
    }
    private static native long init(LibrespotCallbacks callbacks);

    public final void load(@NonNull String src, boolean autoplay) {
        do_load(mNativeObj, src, autoplay);
    }
    private static native void do_load(long self, @NonNull String src, boolean autoplay);

    public final void play() {
        do_play(mNativeObj);
    }
    private static native void do_play(long self);

    public final void pause() {
        do_pause(mNativeObj);
    }
    private static native void do_pause(long self);

    public final void initializeLibrespot(@NonNull String credentials_path, @NonNull String audio_path, @NonNull String access_token) {
        do_initializeLibrespot(mNativeObj, credentials_path, audio_path, access_token);
    }
    private static native void do_initializeLibrespot(long self, @NonNull String credentials_path, @NonNull String audio_path, @NonNull String access_token);

    public static native void initializeAndroidContext();

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ LibrespotWrapper(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}