import { Theme } from "../constants.slint";
import { AppCallbacks } from "../callbacks.slint";

export component Button inherits Rectangle {
    in property <string> text;
    in property <image> icon;
    in property <bool> enabled: true;
    in property <bool> has_custom_layout: false;
    in property <MouseCursor> mouse_cursor: pointer;
    out property <bool> has_hover: touch.has-hover;
    out property <bool> pressed: touch.pressed;

    callback clicked();

    horizontal-stretch: 0;
    border-radius: 13px;
    height: Theme.modelTitle + 10px;
    background: root.text != "" || root.icon.width > 0 ? (
        root.pressed ? Theme.accent.darker(0.15) : (root.has_hover ? Theme.accent.darker(0.08) : Theme.accent)) : (
        !root.enabled ? transparent : (root.pressed ? Theme.textPrimary.with-alpha(0.08) : (root.has_hover ? Theme.textPrimary.with-alpha(0.04) : transparent)));

    animate background {
        duration: 150ms;
        easing: ease-out;
    }
    animate opacity {
        duration: 150ms;
        easing: ease-out;
    }

    content_layout := HorizontalLayout {
        visible: !root.has_custom_layout && (root.text != "" || root.icon.width > 0);
        alignment: center;
        padding-right: 14px;
        padding-left: 14px;
        spacing: 6px;

        if (root.icon.width > 0): VerticalLayout {
            alignment: center;
            Image {
                source: root.icon;
                colorize: Theme.textInverse;
                width: 8px;
                height: 8px;
            }
        }

        if (root.text != ""): Text {
            vertical-alignment: center;
            text: root.text;
            color: Theme.textInverse;
            font-size: Theme.caption;
        }
    }

    touch := TouchArea {
        enabled: root.enabled;
        mouse-cursor: root.enabled ? root.mouse_cursor : default;
        clicked => {
            root.clicked();
        }

        @children
    }
}
