import { Theme } from "../constants.slint";
import { Utils, DefaultIconType } from "../utils.slint";

export component CardView inherits VerticalLayout {
    in property <string> title: @tr("Card Title");
    in property <image> cover-img: @image-url("");
    in property <string> extension: "";
    in property <image> extension_icon: @image-url("");

    padding: Theme.paddingSm;
    spacing: Theme.spacingXs;

    Rectangle {
        border-radius: Theme.borderRadiusMd;
        height: self.width;
        clip: true;

        Image {
            height: parent.height;
            width: parent.width;
            source: Utils.load_image_or_default(root.cover-img, DefaultIconType.Entity);
            horizontal-alignment: center;
            vertical-alignment: center;
            image-fit: cover;
            image-rendering: pixelated;
        }

        if (root.extension != ""): Rectangle {
            x: parent.width - self.width - Theme.paddingSm;
            y: Theme.paddingSm;
            width: Theme.iconSizeSm;
            height: Theme.iconSizeSm;
            background: Theme.primary.with-alpha(0.85);
            border-radius: self.width / 2;

            Image {
                width: parent.width - 4px;
                height: parent.height - 4px;
                x: 2px;
                y: 2px;
                source: Utils.load_image_or_default(root.extension_icon, DefaultIconType.Extension);
            }
        }
    }

    VerticalLayout {
        padding-left: Theme.spacingXxs;
        Text {
            text: root.title;
            font-size: Theme.modelTitle;
            color: Theme.textPrimary;
            horizontal-alignment: start;
            overflow: elide;
        }
    }
}
