import { ListView } from "std-widgets.slint";
import { CardView } from "card_view.slint";
import { Theme } from "../constants.slint";
import { WindowInfo } from "../window_info.slint";

export component GridListView inherits Rectangle {
    clip: true;
    width: 100%;
    in property <length> padding-offset: 0px;
    property <int> max-columns: Math.max(1, Math.floor((WindowInfo.window-width - WindowInfo.sidebar-width - Theme.paddingLg - root.padding-offset) / (root.item-width + root.spacing-x)));
    in property <length> item-width: Theme.cardWidth;
    in property <length> item-height: Theme.cardHeight;
    in property <length> spacing-x: Theme.spacingSm;
    in property <length> spacing-y: Theme.spacingSm;
    in property <int> total-items: 0;

    property <int> total-rows: root.total-items == 0 ? 0 : (root.total-items + root.max-columns - 1) / root.max-columns;
    property <length> scroll-y: 0px;

    pure callback item-title(int) -> string;
    pure callback item-cover(int) -> image;
    pure callback item-extension-icon(int) -> image;
    callback item-clicked(int);

    ListView {
        width: 100%;
        height: 100%;
        vertical-scrollbar-policy: always-on;

        for row-index in root.total-rows: Rectangle {
            height: root.item-height + root.spacing-y;

            HorizontalLayout {
                alignment: start;

                for col-index in 20: col := Rectangle {
                    visible: col-index < root.max-columns;
                    width: self.visible ? root.item-width + ((col-index < root.max-columns - 1) ? root.spacing-x : 0px) : 0px;

                    property <int> item-idx: row-index * root.max-columns + col-index;

                    if (self.visible && self.item-idx < root.total-items): cell := Rectangle {
                        width: root.item-width;
                        height: root.item-height;
                        background: touch.has-hover ? Theme.secondary : transparent;
                        border-radius: Theme.borderRadiusLg;
                        clip: true;

                        CardView {
                            title: root.item-title(col.item-idx);
                            cover-img: root.item-cover(col.item-idx);
                            extension-icon: root.item-extension-icon(col.item-idx);
                        }

                        touch := TouchArea {
                            mouse-cursor: pointer;
                            clicked => {
                                root.item-clicked(col.item-idx);
                            }
                        }
                    }
                }
            }
        }
    }
}
