import { ListView, VerticalBox } from "std-widgets.slint";
import { SongModel } from "../types/song_view.slint";
import { SongListItem } from "song_list_item.slint";
import { SongDetails } from "song_details.slint";
import { Constants, Theme } from "../constants.slint";

export component SongsPageLayout inherits Rectangle {
    in-out property <int> active-idx: -1;
    property <SongModel> active: active-idx >= 0 ? songs[active-idx] : default-song;

    in property <[SongModel]> songs: Constants.testSongs;
    in property <SongModel> default-song: Constants.defaultSong;

    TouchArea {
        width: 100%;
        height: 100%;
        clicked => {
            active-idx = -1;
        }
    }

    HorizontalLayout {
        height: 100%;
        HorizontalLayout {
            horizontal-stretch: 2;
            SongDetails {
                song: active;
            }
        }

        VerticalBox {
            horizontal-stretch: 3;

            ListView {
                vertical-scrollbar-policy: always-on;
                preferred-height: songs.length * Theme.songListItemHeight;

                for song[index] in songs: VerticalLayout {

                    HorizontalLayout {
                        padding-bottom: Theme.paddingSm;
                        padding-right: Theme.spacingXl;

                        Rectangle {
                            SongListItem {
                                song: song;
                                border-width: (active-idx == index || self.has-hover) ? Theme.borderWidth * 2 : 0px;
                                border-color: active-idx == index ? Theme.accent : Theme.accent.darker(0.2);

                                changed pressed => {
                                    if self.pressed {
                                        active-idx = index;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
