import { ListView } from "std-widgets.slint";
import { SongModel } from "../types/song_view.slint";
import { SongListItem } from "song_list_item.slint";
import { Theme, Constants } from "../constants.slint";

export component SongListView inherits Rectangle {
    in property <[SongModel]> songs: Constants.testSongs;
    in-out property <int> active-idx: -1;

    background: transparent;

    ListView {
        width: 100%;
        height: 100%;
        vertical-scrollbar-policy: always-on;

        for song[index] in root.songs: VerticalLayout {
            HorizontalLayout {
                padding-bottom: Theme.paddingSm;
                padding-right: Theme.spacingXl;

                Rectangle {
                    SongListItem {
                        song: song;
                        border-width: (root.active-idx == index || self.has-hover) ? Theme.borderWidth * 2 : 0px;
                        border-color: root.active-idx == index ? Theme.accent : Theme.accent.darker(0.2);

                        changed pressed => {
                            if self.pressed {
                                root.active-idx = index;
                            }
                        }
                    }
                }
            }
        }
    }
}
