name: moosync_flutter
description: Moosync Flutter UI with Rust FFI.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.7.0
  ffi: ^2.1.3
