import { Theme } from "../constants.slint";
import { SongModel, CoverHelper } from "../types/song_view.slint";
import { PlayerProps } from "../props.slint";

export component TrackInfo inherits Rectangle {
    width: Theme.trackInfoWidth;
    height: Theme.topbarHeight;

    property <SongModel> current_song: PlayerProps.current_song;

    HorizontalLayout {
        spacing: Theme.spacingMd;
        alignment: start;

        Rectangle {
            width: Theme.trackInfoThumbnailSize;
            height: Theme.trackInfoThumbnailSize;
            border-radius: Theme.borderRadiusMd;
            background: Theme.secondary;
            border-width: Theme.borderWidth;
            border-color: Theme.textPrimary.with-alpha(0.06);
            clip: true;

            Image {
                width: root.current_song.id == "" ? Theme.iconSizeXl : parent.width;
                height: root.current_song.id == "" ? Theme.iconSizeXl : parent.height;
                source: root.current_song.coverPathLow.width > 0 ? root.current_song.coverPathLow : (root.current_song.id != "" ? CoverHelper.fetch_cover_low(root.current_song) : @image-url("../icons/song_default.svg"));
                image-fit: cover;
                colorize: root.current_song.id == "" ? Theme.textSecondary : transparent;
            }
        }

        // Song Details
        VerticalLayout {
            alignment: center;
            spacing: Theme.spacingTiny;

            Text {
                accessible-role: text;
                accessible-label: root.current_song.title;
                text: root.current_song.title;
                color: Theme.textPrimary; // Text Primary
                font-size: Theme.body;
                font-weight: 600;
                overflow: elide;
            }

            HorizontalLayout {
                spacing: 0px;
                for artist[i] in root.current_song.artists: HorizontalLayout {
                    spacing: 0px;
                    Text {
                        accessible-role: text;
                        accessible-label: artist.title;
                        text: (i > 0 ? ", " : "") + artist.title;
                        color: Theme.textSecondary;
                        font-size: Theme.caption;
                        overflow: elide;
                    }
                }
            }

            Text {
                accessible-role: text;
                accessible-label: root.current_song.album_name;
                text: root.current_song.album_name;
                color: Theme.textSecondary; // Text Secondary
                font-size: Theme.extraSmall;
            }
        }
    }
}
