import { PathSelector } from "path_selector.slint";
import { Theme } from "../constants.slint";
import { PreferenceGroup } from "preference_group.slint";
import { TextInputGroup } from "text_input.slint";
import { ScrollView } from "std-widgets.slint";
import { ToggleGroup } from "toggle.slint";
import { RadioGroup } from "radio_group.slint";
import { DropdownGroup } from "dropdown.slint";
import { NumberInputGroup } from "number_input.slint";
import { ButtonGroup } from "button_group.slint";
import { AppPreferences } from "preferences.slint";
import { SingleFileInput } from "single_file_input.slint";

export component PathsPage inherits VerticalLayout {
    height: 100%;
    padding-top: 15px;
    padding-bottom: 15px;
    padding-right: 15px;
    spacing: Theme.spacingLg;

    HorizontalLayout {
        padding-bottom: Theme.paddingSm;
        Text {
            text: "Settings > Paths";
            font-size: Theme.modelTitle;
            color: Theme.accent;
        }
    }

    ScrollView {
        vertical-stretch: 1;
        VerticalLayout {
            spacing: Theme.spacingLg;
            padding-right: Theme.paddingLg;

            for item in AppPreferences.paths_items: PreferenceGroup {
                if item.kind == "PathSelector": PathSelector {
                    preference: item;
                }
                if item.kind == "SingleFileInput": SingleFileInput {
                    preference: item;
                }
                if item.kind == "NumberInputGroup": NumberInputGroup {
                    preference: item;
                }
                if item.kind == "TextInputGroup": TextInputGroup {
                    preference: item;
                }
                if item.kind == "ToggleGroup": ToggleGroup {
                    preference: item;
                }
                if item.kind == "RadioGroup": RadioGroup {
                    preference: item;
                }
                if item.kind == "DropdownGroup": DropdownGroup {
                    preference: item;
                }
            }
        }
    }
}
