export enum PreferenceType {
    PathSelector,
    SingleFileInput,
    NumberInputGroup,
    TextInputGroup,
    ToggleGroup,
    RadioGroup,
    DropdownGroup,
    TextArrayInput,
}

export struct PreferenceOption {
    id: string,
    label: string,
}

export struct PreferenceItem {
    id: string,
    pref_type: PreferenceType,
    title: string,
    subtitle: string,
    placeholder: string,
    validation: string,
    
    // Values:
    value_string: string,
    value_bool: bool,
    value_number: float,
    value_list: [string],
    
    // Options:
    options: [PreferenceOption],
}

export struct Preferences {
    dummy: bool,
}

export global AppPreferences {
    in-out property <[PreferenceItem]> paths_items: [];
    in-out property <[PreferenceItem]> system_items: [];

    // Keep a dummy property for compile compatibility
    in-out property <Preferences> preferences: { dummy: false };
}
