import { Theme } from "../constants.slint";
export component PreferenceGroup inherits Rectangle {
    border-radius: Theme.borderRadiusXl;
    background: Theme.secondary;
    height: main_layout.preferred-height;

    main_layout := HorizontalLayout {
        padding: Theme.paddingMd;
        VerticalLayout {
            spacing: Theme.spacingMd;
            alignment: start;

            @children
        }
    }
}
