export struct RadioItem {
    id: string,
    label: string,
}

export struct PreferenceItem {
    id: string,
    kind: string,
    title: string,
    subtitle: string,
    placeholder: string,
    
    // Values:
    value_string: string,
    value_bool: bool,
    value_number: float,
    value_list: [string],
    
    // Options:
    options_radio: [RadioItem],
    options_dropdown: [string],
}

export struct Preferences {
    dummy: bool,
}

export global AppPreferences {
    in-out property <[PreferenceItem]> paths_items: [];
    in-out property <[PreferenceItem]> system_items: [];
    in-out property <[PreferenceItem]> extensions_items: [];

    // Keep a dummy property for compile compatibility
    in-out property <Preferences> preferences: { dummy: false };
}
