import { Modal, ModalSize } from "../common/modal.slint";
import { SettingsSidebar, SettingsSidebarItem } from "../sidebar/sidebar.slint";
import {
    Pages,
    SettingsPages,
    Theme,
    ThemeConfig,
    ThemeConstant,
} from "../constants.slint";
import { SettingsPageWrapper } from "../common/page_wrapper.slint";
import { PathSelector } from "path_selector.slint";
import { PathsPage } from "paths.slint";
import { SystemPage } from "system.slint";
import { ExtensionsPage } from "extensions.slint";
import { ExtensionItem } from "../types/extension_view.slint";
import { ThemesPage } from "themes.slint";
import { TextInputGroup } from "text_input.slint";
import { ButtonGroup, ButtonItem } from "button_group.slint";
import { AppCallbacks } from "../callbacks.slint";
import {
    SaveThemeModal,
    SaveThemeState,
} from "../common/save_theme_modal.slint";
import { IconButton } from "../common/icon_button.slint";

export component Settings inherits Modal {
    modalSize: ModalSize.Xl;
    property <SettingsPages> activePage: SettingsPages.Extensions;
    changed activePage => {
        AppCallbacks.settings-active-page-changed(self.activePage);
    }

    in-out property <[ThemeConfig]> available-themes;
    in-out property <string> active-theme-id;
    in-out property <[ThemeConstant]> theme-constants;
    in-out property <[ExtensionItem]> extensions;

    property <[SettingsSidebarItem]> items: [
        {
            text: @tr("Paths"),
            icon: @image-url("../icons/paths.svg"),
            page: SettingsPages.Paths
        },
        {
            text: @tr("System"),
            icon: @image-url("../icons/system.svg"),
            page: SettingsPages.System
        },
        {
            text: @tr("Extensions"),
            icon: @image-url("../icons/extensions.svg"),
            page: SettingsPages.Extensions
        },
        {
            text: @tr("Themes"),
            icon: @image-url("../icons/themes.svg"),
            page: SettingsPages.Themes
        },
    ];

    HorizontalLayout {
        SettingsSidebar {
            sidebarWidth: Theme.settingsSidebarWidth;
            items: items;
            activePage <=> root.activePage;
        }

        Rectangle {
            horizontal-stretch: 1;
            background: Theme.primary;

            TouchArea {
                pointer-event(event) => {
                    if (event.kind == PointerEventKind.down) {
                        if (event.button == PointerEventButton.back) {
                            AppCallbacks.navigate_back();
                        } else if (event.button == PointerEventButton.forward) {
                            AppCallbacks.navigate_forward();
                        }
                    }
                }
            }

            SettingsPageWrapper {
                active-page <=> root.activePage;
                page-type: SettingsPages.Paths;

                PathsPage { }
            }

            SettingsPageWrapper {
                active-page <=> root.activePage;
                page-type: SettingsPages.System;

                SystemPage { }
            }

            SettingsPageWrapper {
                active-page <=> root.activePage;
                page-type: SettingsPages.Extensions;

                ExtensionsPage {
                    extensions <=> root.extensions;
                }
            }

            SettingsPageWrapper {
                active-page <=> root.activePage;
                page-type: SettingsPages.Themes;

                ThemesPage {
                    available-themes <=> root.available-themes;
                    active-theme-id <=> root.active-theme-id;
                    theme-constants <=> root.theme-constants;
                }
            }

            // Close button at top right
            IconButton {
                x: parent.width - self.width - Theme.paddingMd;
                y: Theme.paddingMd;
                width: Theme.settingsCloseButtonSize;
                height: Theme.settingsCloseButtonSize;
                border-radius: Theme.settingsCloseButtonSize / 2;
                icon_source: @image-url("../icons/cross.svg");
                icon_size: Theme.extraSmall;
                clicked => {
                    root.close();
                }
            }
        }
    }

    if SaveThemeState.show_modal: SaveThemeModal {
        close => {
            SaveThemeState.show_modal = false;
        }
    }
}
