import { Modal, ModalSize } from "../common/modal.slint";
import { SettingsSidebar, SettingsSidebarItem } from "../sidebar/sidebar.slint";
import {
    SettingsPages,
    Theme,
} from "../constants.slint";
import { SettingsPageWrapper } from "../common/page_wrapper.slint";
import { PathsPage } from "paths.slint";
import { SystemPage } from "system.slint";
import { ExtensionsPage } from "extensions.slint";
import { ThemesPage } from "themes.slint";
import { AppCallbacks } from "../callbacks.slint";
import {
    SaveThemeModal,
    SaveThemeState,
} from "../common/save_theme_modal.slint";
import { IconButton } from "../common/icon_button.slint";

export global SettingsState {
    in-out property <bool> show_settings: false;
    in-out property <SettingsPages> active_page: SettingsPages.Paths;

    changed show_settings => {
        AppCallbacks.settings-toggled(self.show_settings);
    }
    changed active_page => {
        AppCallbacks.settings-active-page-changed(self.active_page);
    }
}

export component Settings inherits Modal {
    modalSize: ModalSize.Xl;
    in-out property <SettingsPages> active_page <=> SettingsState.active_page;

    property <[SettingsSidebarItem]> items: [
        {
            text: @tr("Paths"),
            icon: @image-url("../icons/paths.svg"),
            page: SettingsPages.Paths,
            accessible_label: @tr("Settings Paths")
        },
        {
            text: @tr("System"),
            icon: @image-url("../icons/system.svg"),
            page: SettingsPages.System,
            accessible_label: @tr("Settings System")
        },
        {
            text: @tr("Extensions"),
            icon: @image-url("../icons/extensions.svg"),
            page: SettingsPages.Extensions,
            accessible_label: @tr("Settings Extensions")
        },
        {
            text: @tr("Themes"),
            icon: @image-url("../icons/themes.svg"),
            page: SettingsPages.Themes,
            accessible_label: @tr("Settings Themes")
        },
    ];

    HorizontalLayout {
        SettingsSidebar {
            sidebar_width: Theme.settingsSidebarWidth;
            items: items;
            active_page <=> root.active_page;
        }

        Rectangle {
            horizontal-stretch: 1;
            background: Theme.primary;

            TouchArea {
                pointer-event(event) => {
                    if (event.kind == PointerEventKind.down) {
                        if (event.button == PointerEventButton.back) {
                            AppCallbacks.navigate_back();
                        } else if (event.button == PointerEventButton.forward) {
                            AppCallbacks.navigate_forward();
                        }
                    }
                }
            }

            SettingsPageWrapper {
                active-page <=> root.active_page;
                page-type: SettingsPages.Paths;

                PathsPage { }
            }

            SettingsPageWrapper {
                active-page <=> root.active_page;
                page-type: SettingsPages.System;

                SystemPage { }
            }

            SettingsPageWrapper {
                active-page <=> root.active_page;
                page-type: SettingsPages.Extensions;

                ExtensionsPage { }
            }

            SettingsPageWrapper {
                active-page <=> root.active_page;
                page-type: SettingsPages.Themes;

                ThemesPage { }
            }

            // Close button at top right
            IconButton {
                x: parent.width - self.width - Theme.paddingMd;
                y: Theme.paddingMd;
                width: Theme.settingsCloseButtonSize;
                height: Theme.settingsCloseButtonSize;
                border-radius: Theme.settingsCloseButtonSize / 2;
                icon_source: @image-url("../icons/cross.svg");
                icon_size: Theme.extraSmall;
                clicked => {
                    root.close();
                }
            }
        }
    }

    if SaveThemeState.show_modal: SaveThemeModal {
        close => {
            SaveThemeState.show_modal = false;
        }
    }
}
