import { Theme } from "../constants.slint";
import { PreferenceItem } from "preferences.slint";
import { AppCallbacks } from "../callbacks.slint";

export component SingleFileInput inherits VerticalLayout {
    in property <PreferenceItem> preference;
    in property <string> title: root.preference.title;
    in property <string> subtitle: root.preference.subtitle;
    in-out property <string> value: root.preference.value_string;

    callback browse_clicked();

    spacing: Theme.spacingMd;
    alignment: start;

    VerticalLayout {
        Text {
            text: root.title;
            font-size: Theme.modelTitle;
            color: Theme.textPrimary;
        }

        Text {
            text: root.subtitle;
            font-size: Theme.caption;
            wrap: word-wrap;
            color: Theme.textSecondary;
        }
    }

    HorizontalLayout {
        spacing: Theme.spacingMd;

        Rectangle {
            border-radius: Theme.borderRadiusXl;
            border-color: Theme.textSecondary;
            border-width: 1px;
            height: Theme.fileInputHeight;
            horizontal-stretch: 1;

            HorizontalLayout {
                padding-left: Theme.paddingMd;
                padding-right: Theme.paddingMd;

                Text {
                    text: root.value;
                    vertical-alignment: center;
                    color: Theme.textPrimary;
                    font-size: Theme.caption;
                }

                TouchArea {
                    clicked => {
                        let chosen = AppCallbacks.open_directory_picker();
                        if (chosen != "") {
                            if (root.preference.id != "") {
                                AppCallbacks.preference_changed({ id: root.preference.id, value_string: chosen, value_bool: false, value_number: 0.0 });
                            }
                            root.value = chosen;
                            root.browse_clicked();
                        }
                    }

                    HorizontalLayout {
                        padding: 10px;
                        Image {
                            source: @image-url("../icons/folder.svg");
                            colorize: Theme.textPrimary;
                            width: Theme.iconSizeMd;
                        }
                    }
                }
            }
        }
    }
}
