import { Theme } from "../constants.slint";
import { ScrollView } from "std-widgets.slint";
import { AppPreferences } from "preferences.slint";
import { PreferenceList } from "preference_list.slint";

export component SystemPage inherits VerticalLayout {
    height: 100%;
    padding-top: 15px;
    padding-bottom: 15px;
    padding-right: 15px;
    spacing: Theme.spacingLg;

    HorizontalLayout {
        padding-bottom: Theme.paddingSm;
        Text {
            text: @tr("Settings > System");
            font-size: Theme.modelTitle;
            color: Theme.accent;
        }
    }

    ScrollView {
        vertical-stretch: 1;
        VerticalLayout {
            spacing: Theme.spacingLg;
            padding-right: Theme.paddingLg;

            PreferenceList {
                items: AppPreferences.system_items;
            }
        }
    }
}
