import { Theme } from "../constants.slint";
import { ScrollView } from "std-widgets.slint";
import { PreferenceItem } from "preferences.slint";
import { AppCallbacks, UtilCallbacks } from "../callbacks.slint";
import { Button } from "../common/button.slint";
import { IconButton } from "../common/icon_button.slint";

export component TextArrayInput inherits VerticalLayout {
    in property <PreferenceItem> preference;
    in property <string> title: root.preference.title;
    in property <string> subtitle: root.preference.subtitle;
    in property <string> placeholder: root.preference.placeholder;
    in property <string> validation: root.preference.validation;
    in property <[string]> items: root.preference.value_list;

    property <string> new_text: "";
    property <bool> is_valid: root.new_text == "" || root.validation == "" || UtilCallbacks.validate_input(root.new_text, root.validation);

    callback added(string);
    callback removed(string);

    spacing: Theme.spacingSm;

    VerticalLayout {
        spacing: Theme.spacingXs;
        Text {
            text: root.title;
            font-size: Theme.modelTitle;
            color: Theme.textPrimary;
        }

        if root.subtitle != "": Text {
            text: root.subtitle;
            font-size: Theme.caption;
            color: Theme.textSecondary;
            wrap: word-wrap;
        }
    }

    HorizontalLayout {
        spacing: Theme.spacingMd;
        height: Theme.textInputHeight;

        Rectangle {
            horizontal-stretch: 1;
            border-radius: Theme.borderRadiusXl;
            border-color: (root.new_text != "" && !root.is_valid) ? Theme.danger : (text_input.has-focus ? Theme.accent : Theme.textSecondary);
            border-width: 1px;
            clip: true;

            HorizontalLayout {
                padding-left: Theme.paddingMd;
                padding-right: Theme.paddingMd;

                Rectangle {
                    horizontal-stretch: 1;
                    min-width: 0px;
                    clip: true;
                    if (text_input.text == "" && root.placeholder != ""): Text {
                        text: root.placeholder;
                        color: Theme.textSecondary;
                        font-size: Theme.body;
                        vertical-alignment: center;
                        overflow: elide;
                    }
                    text_input := TextInput {
                        property <length> computed_x;

                        x: Math.min(0px, Math.max(parent.width - self.width - self.text-cursor-width, self.computed_x));
                        width: Math.max(parent.width - self.text-cursor-width, self.preferred-width);
                        height: 100%;
                        vertical-alignment: center;
                        color: Theme.textPrimary;
                        font-size: Theme.body;
                        single-line: true;

                        cursor-position-changed(cursor-position) => {
                            if cursor-position.x + self.computed_x < 0px {
                                self.computed_x = - cursor-position.x;
                            } else if cursor-position.x + self.computed_x > parent.width - self.text-cursor-width {
                                self.computed_x = parent.width - cursor-position.x - self.text-cursor-width;
                            }
                        }

                        edited => {
                            root.new_text = self.text;
                        }
                    }
                }
            }
        }

        Button {
            text: @tr("Add");
            icon: @image-url("../icons/plus.svg");
            clicked => {
                if (root.new_text != "" && root.is_valid) {
                    if (root.preference.id != "") {
                        AppCallbacks.preference_changed({
                            id: root.preference.id,
                            value_string: root.new_text,
                            value_bool: false,
                            value_number: 0.0,
                            value_list: []
                        });
                    }
                    root.added(root.new_text);
                    text_input.text = "";
                    root.new_text = "";
                }
            }
        }
    }

    ScrollView {
        height: 120px;
        VerticalLayout {
            spacing: Theme.spacingXxs;
            padding-right: Theme.paddingLg;

            for item in root.items: Rectangle {
                border-radius: Theme.borderRadiusLg;
                border-width: 1px;
                border-color: Theme.textSecondary;

                HorizontalLayout {
                    padding-top: 10px;
                    padding-bottom: 10px;
                    padding-left: 12px;
                    padding-right: 12px;
                    spacing: Theme.spacingMd;

                    Text {
                        text: item;
                        horizontal-stretch: 1;
                        vertical-alignment: center;
                        color: Theme.textPrimary;
                        font-size: Theme.body;
                        overflow: elide;
                    }

                    IconButton {
                        icon_source: @image-url("../icons/cross.svg");
                        icon_size: 8px;
                        width: Theme.iconSizeMd;
                        height: Theme.iconSizeMd;
                        clicked => {
                            if (root.preference.id != "") {
                                AppCallbacks.preference_changed({
                                    id: root.preference.id,
                                    value_string: item,
                                    value_bool: false,
                                    value_number: 0.0,
                                    value_list: []
                                });
                            }
                            root.removed(item);
                        }
                    }
                }
            }
        }
    }
}
