import { Theme } from "../constants.slint";
import { LineEdit } from "std-widgets.slint";
import { PreferenceItem } from "preferences.slint";
import { AppCallbacks } from "../callbacks.slint";

export component TextInputGroup inherits VerticalLayout {
    in property <PreferenceItem> preference;
    in property <string> title: root.preference.title;
    in property <string> subtitle: root.preference.subtitle;
    in property <string> placeholder: root.preference.placeholder;
    in property <InputType> inputType;

    in-out property <string> value: root.preference.value_string;
    callback edited(string);

    spacing: Theme.spacingXs;
    alignment: start;

    VerticalLayout {
        spacing: Theme.spacingXs;
        Text {
            text: root.title;
            font-size: Theme.modelTitle;
            color: Theme.textPrimary;
        }

        if root.subtitle != "": Text {
            text: root.subtitle;
            font-size: Theme.caption;
            color: Theme.textSecondary;
        }
    }

    TouchArea {
        height: Theme.textInputHeight;
        clicked => {
            text_input.focus();
        }
        Rectangle {
            border-radius: Theme.borderRadiusXl;
            border-color: parent.has-hover || text_input.has-focus ? Theme.accent : Theme.textSecondary;
            border-width: 1px;

            HorizontalLayout {
                padding-left: Theme.paddingMd;
                padding-right: Theme.paddingMd;
                Rectangle {
                    horizontal-stretch: 1;
                    if (text_input.text == "" && root.placeholder != ""): Text {
                        text: root.placeholder;
                        color: Theme.textSecondary;
                        font-size: Theme.body;
                        vertical-alignment: center;
                        x: 0px;
                    }
                    text_input := TextInput {
                        width: 100%;
                        height: 100%;
                        text <=> root.value;
                        color: Theme.textPrimary;
                        font-size: Theme.body;
                        input-type: root.inputType;
                        vertical-alignment: center;
                        single-line: true;
                        edited => {
                            if (root.preference.id != "") {
                                AppCallbacks.preference_changed({ id: root.preference.id, value_string: self.text, value_bool: false, value_number: 0.0 });
                            }
                            root.edited(self.text);
                        }
                    }
                }
            }
        }
    }
}
