[package]
name = "types"
edition = "2021"
version = "0.1.0"

[dependencies]
serde_json = { version = "1.0" }
thiserror = "2.0.12"
tracing = { version = "0.1.41", default-features = false, features = [
    "attributes",
] }
async-trait = { version = "0.1.88", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = { version = "0.6", features = [], optional = true }
uuid = { version = "1.17.0", default-features = false, optional = true, features = [
    "v4",
] }
wasm-bindgen = { version = "0.2", optional = true, default-features = false }
bitcode = { version = "0.6.6" }
extism-convert = { version = "1.11.1", optional = true }
diesel = { version = "2.2.0", features = ["sqlite", "chrono", "serde_json"], optional = true }
oauth2 = { version = "5.0", optional = true }

[features]
ui = ["dep:wasm-bindgen", "dep:serde-wasm-bindgen"]
extensions = ["dep:extism-convert"]
extensions-core = ["dep:extism-convert", "dep:uuid"]
core = [
    "dep:extism-convert",
    "dep:uuid",
    "dep:diesel",
    "dep:oauth2",
]
default = ["core"]
