// @generated by protoc-gen-es v1.10.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file core/types/protos/songs.proto (package moosync.types, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum moosync.types.SongType
 */
export declare enum SongType {
  /**
   * @generated from enum value: LOCAL = 0;
   */
  LOCAL = 0,

  /**
   * @generated from enum value: URL = 1;
   */
  URL = 1,

  /**
   * @generated from enum value: SPOTIFY = 2;
   */
  SPOTIFY = 2,

  /**
   * @generated from enum value: DASH = 3;
   */
  DASH = 3,

  /**
   * @generated from enum value: HLS = 4;
   */
  HLS = 4,
}

/**
 * @generated from message moosync.types.Album
 */
export declare class Album extends Message<Album> {
  /**
   * @generated from field: optional string album_id = 1;
   */
  albumId?: string;

  /**
   * @generated from field: optional string album_name = 2;
   */
  albumName?: string;

  /**
   * @generated from field: optional string album_artist = 3;
   */
  albumArtist?: string;

  /**
   * @generated from field: optional string album_coverpath_high = 4;
   */
  albumCoverpathHigh?: string;

  /**
   * @generated from field: double album_song_count = 5;
   */
  albumSongCount: number;

  /**
   * @generated from field: optional string year = 6;
   */
  year?: string;

  /**
   * @generated from field: optional string album_coverpath_low = 7;
   */
  albumCoverpathLow?: string;

  constructor(data?: PartialMessage<Album>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "moosync.types.Album";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Album;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Album;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Album;

  static equals(a: Album | PlainMessage<Album> | undefined, b: Album | PlainMessage<Album> | undefined): boolean;
}

/**
 * @generated from message moosync.types.Artist
 */
export declare class Artist extends Message<Artist> {
  /**
   * @generated from field: optional string artist_id = 1;
   */
  artistId?: string;

  /**
   * @generated from field: optional string artist_mbid = 2;
   */
  artistMbid?: string;

  /**
   * @generated from field: optional string artist_name = 3;
   */
  artistName?: string;

  /**
   * @generated from field: optional string artist_coverpath = 4;
   */
  artistCoverpath?: string;

  /**
   * @generated from field: double artist_song_count = 5;
   */
  artistSongCount: number;

  /**
   * @generated from field: optional string sanitized_artist_name = 7;
   */
  sanitizedArtistName?: string;

  constructor(data?: PartialMessage<Artist>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "moosync.types.Artist";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Artist;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Artist;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Artist;

  static equals(a: Artist | PlainMessage<Artist> | undefined, b: Artist | PlainMessage<Artist> | undefined): boolean;
}

/**
 * @generated from message moosync.types.Genre
 */
export declare class Genre extends Message<Genre> {
  /**
   * @generated from field: optional string genre_id = 1;
   */
  genreId?: string;

  /**
   * @generated from field: optional string genre_name = 2;
   */
  genreName?: string;

  /**
   * @generated from field: double genre_song_count = 3;
   */
  genreSongCount: number;

  constructor(data?: PartialMessage<Genre>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "moosync.types.Genre";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Genre;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Genre;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Genre;

  static equals(a: Genre | PlainMessage<Genre> | undefined, b: Genre | PlainMessage<Genre> | undefined): boolean;
}

/**
 * @generated from message moosync.types.Playlist
 */
export declare class Playlist extends Message<Playlist> {
  /**
   * @generated from field: optional string playlist_id = 1;
   */
  playlistId?: string;

  /**
   * @generated from field: string playlist_name = 2;
   */
  playlistName: string;

  /**
   * @generated from field: optional string playlist_coverpath = 3;
   */
  playlistCoverpath?: string;

  /**
   * @generated from field: double playlist_song_count = 4;
   */
  playlistSongCount: number;

  /**
   * @generated from field: optional string playlist_desc = 5;
   */
  playlistDesc?: string;

  /**
   * @generated from field: optional string playlist_path = 6;
   */
  playlistPath?: string;

  /**
   * @generated from field: optional string extension = 7;
   */
  extension?: string;

  /**
   * @generated from field: optional string icon = 8;
   */
  icon?: string;

  /**
   * @generated from field: optional bool library_item = 9;
   */
  libraryItem?: boolean;

  constructor(data?: PartialMessage<Playlist>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "moosync.types.Playlist";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Playlist;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Playlist;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Playlist;

  static equals(a: Playlist | PlainMessage<Playlist> | undefined, b: Playlist | PlainMessage<Playlist> | undefined): boolean;
}

/**
 * @generated from message moosync.types.InnerSong
 */
export declare class InnerSong extends Message<InnerSong> {
  /**
   * _id
   *
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string path = 2;
   */
  path?: string;

  /**
   * @generated from field: optional double size = 3;
   */
  size?: number;

  /**
   * @generated from field: optional string inode = 4;
   */
  inode?: string;

  /**
   * @generated from field: optional string deviceno = 5;
   */
  deviceno?: string;

  /**
   * @generated from field: optional string title = 6;
   */
  title?: string;

  /**
   * @generated from field: optional string date = 7;
   */
  date?: string;

  /**
   * @generated from field: optional string year = 8;
   */
  year?: string;

  /**
   * @generated from field: optional string lyrics = 9;
   */
  lyrics?: string;

  /**
   * @generated from field: optional string release_type = 10;
   */
  releaseType?: string;

  /**
   * @generated from field: optional double bitrate = 11;
   */
  bitrate?: number;

  /**
   * @generated from field: optional string codec = 12;
   */
  codec?: string;

  /**
   * @generated from field: optional string container = 13;
   */
  container?: string;

  /**
   * @generated from field: optional double duration = 14;
   */
  duration?: number;

  /**
   * @generated from field: optional double sample_rate = 15;
   */
  sampleRate?: number;

  /**
   * @generated from field: optional string hash = 16;
   */
  hash?: string;

  /**
   * @generated from field: moosync.types.SongType type = 17;
   */
  type: SongType;

  /**
   * @generated from field: optional string url = 18;
   */
  url?: string;

  /**
   * @generated from field: optional string song_cover_path_high = 19;
   */
  songCoverPathHigh?: string;

  /**
   * @generated from field: optional string playback_url = 20;
   */
  playbackUrl?: string;

  /**
   * @generated from field: optional string song_cover_path_low = 21;
   */
  songCoverPathLow?: string;

  /**
   * @generated from field: optional int64 date_added = 22;
   */
  dateAdded?: bigint;

  /**
   * @generated from field: optional string provider_extension = 23;
   */
  providerExtension?: string;

  /**
   * @generated from field: optional string icon = 24;
   */
  icon?: string;

  /**
   * @generated from field: optional bool show_in_library = 25;
   */
  showInLibrary?: boolean;

  /**
   * @generated from field: optional double track_no = 26;
   */
  trackNo?: number;

  /**
   * @generated from field: optional bool library_item = 27;
   */
  libraryItem?: boolean;

  constructor(data?: PartialMessage<InnerSong>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "moosync.types.InnerSong";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InnerSong;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InnerSong;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InnerSong;

  static equals(a: InnerSong | PlainMessage<InnerSong> | undefined, b: InnerSong | PlainMessage<InnerSong> | undefined): boolean;
}

/**
 * @generated from message moosync.types.SearchableSong
 */
export declare class SearchableSong extends Message<SearchableSong> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string path = 2;
   */
  path?: string;

  /**
   * @generated from field: optional string title = 3;
   */
  title?: string;

  /**
   * @generated from field: optional double sample_rate = 4;
   */
  sampleRate?: number;

  /**
   * @generated from field: optional string hash = 5;
   */
  hash?: string;

  /**
   * @generated from field: optional moosync.types.SongType type = 6;
   */
  type?: SongType;

  /**
   * @generated from field: optional string url = 7;
   */
  url?: string;

  /**
   * @generated from field: optional string playback_url = 8;
   */
  playbackUrl?: string;

  /**
   * @generated from field: optional string provider_extension = 9;
   */
  providerExtension?: string;

  /**
   * @generated from field: optional bool show_in_library = 10;
   */
  showInLibrary?: boolean;

  constructor(data?: PartialMessage<SearchableSong>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "moosync.types.SearchableSong";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchableSong;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchableSong;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchableSong;

  static equals(a: SearchableSong | PlainMessage<SearchableSong> | undefined, b: SearchableSong | PlainMessage<SearchableSong> | undefined): boolean;
}

/**
 * @generated from message moosync.types.GetSongOptions
 */
export declare class GetSongOptions extends Message<GetSongOptions> {
  /**
   * @generated from field: optional moosync.types.SearchableSong song = 1;
   */
  song?: SearchableSong;

  /**
   * @generated from field: optional moosync.types.Artist artist = 2;
   */
  artist?: Artist;

  /**
   * @generated from field: optional moosync.types.Album album = 3;
   */
  album?: Album;

  /**
   * @generated from field: optional moosync.types.Genre genre = 4;
   */
  genre?: Genre;

  /**
   * @generated from field: optional moosync.types.Playlist playlist = 5;
   */
  playlist?: Playlist;

  /**
   * @generated from field: optional bool inclusive = 6;
   */
  inclusive?: boolean;

  constructor(data?: PartialMessage<GetSongOptions>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "moosync.types.GetSongOptions";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSongOptions;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSongOptions;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSongOptions;

  static equals(a: GetSongOptions | PlainMessage<GetSongOptions> | undefined, b: GetSongOptions | PlainMessage<GetSongOptions> | undefined): boolean;
}

/**
 * @generated from message moosync.types.Song
 */
export declare class Song extends Message<Song> {
  /**
   * @generated from field: moosync.types.InnerSong song = 1;
   */
  song?: InnerSong;

  /**
   * @generated from field: optional moosync.types.Album album = 2;
   */
  album?: Album;

  /**
   * @generated from field: repeated moosync.types.Artist artists = 3;
   */
  artists: Artist[];

  /**
   * @generated from field: repeated moosync.types.Genre genre = 4;
   */
  genre: Genre[];

  constructor(data?: PartialMessage<Song>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "moosync.types.Song";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Song;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Song;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Song;

  static equals(a: Song | PlainMessage<Song> | undefined, b: Song | PlainMessage<Song> | undefined): boolean;
}

/**
 * @generated from message moosync.types.AllAnalytics
 */
export declare class AllAnalytics extends Message<AllAnalytics> {
  /**
   * @generated from field: double total_listen_time = 1;
   */
  totalListenTime: number;

  /**
   * @generated from field: repeated moosync.types.AllAnalytics.SongListenTime songs = 2;
   */
  songs: AllAnalytics_SongListenTime[];

  constructor(data?: PartialMessage<AllAnalytics>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "moosync.types.AllAnalytics";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AllAnalytics;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AllAnalytics;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AllAnalytics;

  static equals(a: AllAnalytics | PlainMessage<AllAnalytics> | undefined, b: AllAnalytics | PlainMessage<AllAnalytics> | undefined): boolean;
}

/**
 * @generated from message moosync.types.AllAnalytics.SongListenTime
 */
export declare class AllAnalytics_SongListenTime extends Message<AllAnalytics_SongListenTime> {
  /**
   * @generated from field: string song_id = 1;
   */
  songId: string;

  /**
   * @generated from field: double time = 2;
   */
  time: number;

  constructor(data?: PartialMessage<AllAnalytics_SongListenTime>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "moosync.types.AllAnalytics.SongListenTime";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AllAnalytics_SongListenTime;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AllAnalytics_SongListenTime;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AllAnalytics_SongListenTime;

  static equals(a: AllAnalytics_SongListenTime | PlainMessage<AllAnalytics_SongListenTime> | undefined, b: AllAnalytics_SongListenTime | PlainMessage<AllAnalytics_SongListenTime> | undefined): boolean;
}

/**
 * @generated from message moosync.types.SearchResult
 */
export declare class SearchResult extends Message<SearchResult> {
  /**
   * @generated from field: repeated moosync.types.Song songs = 1;
   */
  songs: Song[];

  /**
   * @generated from field: repeated moosync.types.Artist artists = 2;
   */
  artists: Artist[];

  /**
   * @generated from field: repeated moosync.types.Playlist playlists = 3;
   */
  playlists: Playlist[];

  /**
   * @generated from field: repeated moosync.types.Album albums = 4;
   */
  albums: Album[];

  /**
   * @generated from field: repeated moosync.types.Genre genres = 5;
   */
  genres: Genre[];

  constructor(data?: PartialMessage<SearchResult>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "moosync.types.SearchResult";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchResult;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchResult;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchResult;

  static equals(a: SearchResult | PlainMessage<SearchResult> | undefined, b: SearchResult | PlainMessage<SearchResult> | undefined): boolean;
}

/**
 * @generated from message moosync.types.GetEntityOptions
 */
export declare class GetEntityOptions extends Message<GetEntityOptions> {
  /**
   * @generated from field: optional moosync.types.Artist artist = 1;
   */
  artist?: Artist;

  /**
   * @generated from field: optional moosync.types.Album album = 2;
   */
  album?: Album;

  /**
   * @generated from field: optional moosync.types.Genre genre = 3;
   */
  genre?: Genre;

  /**
   * @generated from field: optional moosync.types.Playlist playlist = 4;
   */
  playlist?: Playlist;

  /**
   * @generated from field: optional bool inclusive = 5;
   */
  inclusive?: boolean;

  constructor(data?: PartialMessage<GetEntityOptions>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "moosync.types.GetEntityOptions";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEntityOptions;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEntityOptions;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEntityOptions;

  static equals(a: GetEntityOptions | PlainMessage<GetEntityOptions> | undefined, b: GetEntityOptions | PlainMessage<GetEntityOptions> | undefined): boolean;
}

