export enum ProviderScopes {
	SEARCH = 0,
	PLAYLISTS = 1,
	PLAYLIST_SONGS = 2,
	ARTIST_SONGS = 3,
	ALBUM_SONGS = 4,
	RECOMMENDATIONS = 5,
	SCROBBLES = 6,
	PLAYLIST_FROM_URL = 7,
	SONG_FROM_URL = 8,
	SEARCH_ALBUM = 9,
	SEARCH_ARTIST = 10,
}

export const FAVORITES_PLAYLIST_ID = "favorites_playlist";
