import { Theme } from "../constants.slint";
import { IconButton } from "../common/icon_button.slint";

export component SidebarHeader inherits Rectangle {
    height: Theme.sidebarHeaderHeight;

    HorizontalLayout {
        padding-right: Theme.spacingXl;
        alignment: start;
        padding-left: Theme.iconSizeLg + Theme.spacingSm / 2;

        VerticalLayout {
            alignment: center;
            IconButton {
                icon_source: @image-url("../icons/sidebar_toggle.svg");
                icon_width: Theme.playbackControlsIconSize;
                icon_height: Theme.iconSizeMd;
                width: Theme.sidebarHeaderToggleSize;
                height: Theme.sidebarHeaderToggleSize;
            }
        }
    }
}
