import { Theme } from "../constants.slint";
import { IconButton } from "../common/icon_button.slint";

export component SidebarHeader inherits Rectangle {
    in property <bool> collapsed: false;
    callback toggle();

    height: Theme.sidebarHeaderHeight;

    HorizontalLayout {
        padding-right: root.collapsed ? 0px : Theme.spacingXl;
        alignment: root.collapsed ? center : start;
        padding-left: root.collapsed ? 0px : (Theme.iconSizeLg + Theme.spacingSm / 2);

        VerticalLayout {
            alignment: center;
            IconButton {
                icon_source: @image-url("../icons/sidebar_toggle.svg");
                icon_width: Theme.playbackControlsIconSize;
                icon_height: Theme.iconSizeMd;
                width: Theme.sidebarHeaderToggleSize;
                height: Theme.sidebarHeaderToggleSize;
                clicked => {
                    root.toggle();
                }
            }
        }
    }
}
