load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

py_binary(
    name = "replace_bin",
    srcs = ["replace.py"],
    main = "replace.py",
)

py_binary(
    name = "html_generator",
    srcs = ["gen_html.py"],
    main = "gen_html.py",
)
