import { AlbumModel } from "../types/song_view.slint";
import { GridPageLayout } from "../common/grid_page_layout.slint";
import { Constants, Pages } from "../constants.slint";
import { AppProps } from "../props.slint";

export global AlbumsPageProps {
    in-out property <[AlbumModel]> albums: Constants.testAlbums;
    in-out property <AlbumModel> selected-album;
}

export component AlbumsPage inherits Rectangle {
    background: transparent;

    GridPageLayout {
        title: @tr("Albums");
        total_items: AlbumsPageProps.albums.length;
        item_title(idx) => {
            AlbumsPageProps.albums[idx].title
        }
        item_cover(idx) => {
            AlbumsPageProps.albums[idx].coverPath
        }
        item_extension(idx) => {
            AlbumsPageProps.albums[idx].extension
        }
        item_extension_icon(idx) => {
            AlbumsPageProps.albums[idx].extension_icon
        }
        item_clicked(idx) => {
            AlbumsPageProps.selected-album = AlbumsPageProps.albums[idx];
            AppProps.active_page = Pages.AlbumContent;
        }
    }
}
