import { ListView, VerticalBox } from "std-widgets.slint";
import { SongModel } from "../types/song_view.slint";
import { SongListItem } from "../common/song_list_item.slint";
import { SongDetails } from "../common/song_details.slint";
import { Constants, Theme } from "../constants.slint";

export component AllSongs inherits Rectangle {
    property <int> activeIdx: -1;
    property <SongModel> active: activeIdx >= 0 ? songs[activeIdx] : Constants.defaultSong;

    in property <[SongModel]> songs: Constants.testSongs;

    TouchArea {
        width: 100%;
        height: 100%;
        clicked => {
            activeIdx = -1;
        }
    }

    HorizontalLayout {
        height: 100%;
        HorizontalLayout {
            horizontal-stretch: 1;
            SongDetails {
                song: active;
            }
        }

        VerticalBox {
            horizontal-stretch: 2;

            ListView {
                vertical-scrollbar-policy: always-on;
                preferred-height: songs.length * Theme.songListItemHeight;

                for song[index] in songs: VerticalLayout {

                    HorizontalLayout {
                        padding-bottom: Theme.paddingSm;
                        padding-right: Theme.spacingXl;

                        Rectangle {
                            SongListItem {
                                song: song;
                                border-width: (activeIdx == index || self.has-hover) ? Theme.borderWidth * 2 : 0px;
                                border-color: activeIdx == index ? Theme.accent : Theme.accent.darker(0.2);

                                changed pressed => {
                                    if self.pressed {
                                        activeIdx = index;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
