import { SongsPageLayout } from "../common/songs_page_layout.slint";
import { SongModel, ArtistModel } from "../types/song_view.slint";
import { ExtensionProviderItem } from "../types/extension_view.slint";
import { Constants } from "../constants.slint";
import { AppCallbacks } from "../callbacks.slint";
import { ArtistsPageProps } from "./artists.slint";

export global ArtistContentPageProps {
    in-out property <[SongModel]> songs: Constants.testSongs;
    in-out property <[ExtensionProviderItem]> extension_providers: [];
}

export component ArtistContent inherits Rectangle {
    SongsPageLayout {
        songs <=> ArtistContentPageProps.songs;
        extension_providers <=> ArtistContentPageProps.extension_providers;
        provider_toggled(id, enabled) => {
            AppCallbacks.toggle_artist_content_extension(id, enabled);
        }
        load_more => {
            AppCallbacks.load_more_artist_content();
        }
        default-song: {
            id: "",
            title: ArtistsPageProps.selected-artist.title,
            coverPathHigh: ArtistsPageProps.selected-artist.coverPath,
            coverPathLow: ArtistsPageProps.selected-artist.coverPath,
            extension-icon: @image-url("../icons/song_default.svg"),
        };
    }
}
