import { SongsPageLayout } from "../common/songs_page_layout.slint";
import { SongModel } from "../types/song_view.slint";
import { Constants, SelectedEntity } from "../constants.slint";

export component ArtistContent inherits Rectangle {
    in property <SelectedEntity> entity;
    in property <[SongModel]> songs;

    SongsPageLayout {
        songs <=> root.songs;
        default-song: {
            id: "",
            title: entity.title,
            coverPathHigh: entity.cover-path,
            coverPathLow: entity.cover-path,
            extensionIcon: @image-url("../icons/song_default.svg"),
        };
    }
}
