import { GenreModel } from "../types/song_view.slint";
import { GridListView } from "../common/grid_list_view.slint";
import { Constants, Theme, Pages, SelectedEntity } from "../constants.slint";

export component GenresPage inherits Rectangle {
    in property <[GenreModel]> genres: Constants.testGenres;
    in-out property <Pages> active-page;
    in-out property <SelectedEntity> selected-entity;

    background: transparent;

    VerticalLayout {
        spacing: Theme.spacingXxl;
        alignment: start;

        text := Text {
            height: Theme.pageHeader + Theme.paddingLg;
            text: "Genres";
            font-size: Theme.pageHeader;
            color: Theme.textPrimary;
        }

        GridListView {
            height: root.height - text.height - (Theme.spacingXxl + Theme.paddingLg);
            item-width: Theme.cardWidth;
            total-items: root.genres.length;
            item-title(idx) => {
                root.genres[idx].title
            }
            item-cover(idx) => {
                root.genres[idx].coverPath
            }
            item-clicked(idx) => {
                root.selected-entity = {
                    id: root.genres[idx].id,
                    title: root.genres[idx].title,
                    cover-path: root.genres[idx].coverPath,
                };
                root.active-page = Pages.GenreContent;
            }
        }
    }
}
