import { SongsPageLayout } from "../common/songs_page_layout.slint";
import { SongModel, GenreModel } from "../types/song_view.slint";
import { Constants } from "../constants.slint";
import { GenresPageProps } from "./genres.slint";

export global GenreContentPageProps {
    in-out property <[SongModel]> songs: Constants.testSongs;
}

export component GenreContent inherits Rectangle {
    SongsPageLayout {
        songs <=> GenreContentPageProps.songs;
        default-song: {
            id: "",
            title: GenresPageProps.selected-genre.title,
            coverPathHigh: GenresPageProps.selected-genre.coverPath,
            coverPathLow: GenresPageProps.selected-genre.coverPath,
            extension-icon: @image-url("../icons/song_default.svg"),
        };
    }
}
