import { GenreModel } from "../types/song_view.slint";
import { GridListView } from "../common/grid_list_view.slint";
import { Constants, Theme } from "../constants.slint";

export component GenresPage inherits Rectangle {
    in property <[GenreModel]> genres: Constants.testGenres;

    background: transparent;

    VerticalLayout {
        spacing: Theme.spacingXxl;
        alignment: start;

        text := Text {
            height: Theme.pageHeader + Theme.paddingLg;
            text: "Genres";
            font-size: Theme.pageHeader;
            color: Theme.textPrimary;
        }

        GridListView {
            height: root.height - text.height - (Theme.spacingXxl + Theme.paddingLg);
            item-width: Theme.cardWidth;
            total-items: root.genres.length;
            item-title(idx) => {
                root.genres[idx].title
            }
            item-cover(idx) => {
                root.genres[idx].coverPath
            }
        }
    }
}
