import { SongsPageLayout } from "../common/songs_page_layout.slint";
import { SongModel, PlaylistModel } from "../types/song_view.slint";
import { Constants } from "../constants.slint";
import { PlaylistsPageProps } from "./playlists.slint";

export global PlaylistContentPageProps {
    in-out property <[SongModel]> songs: Constants.testSongs;
}

export component PlaylistContent inherits Rectangle {
    SongsPageLayout {
        songs <=> PlaylistContentPageProps.songs;
        default-song: {
            id: "",
            title: PlaylistsPageProps.selected-playlist.title,
            coverPathHigh: PlaylistsPageProps.selected-playlist.coverPath,
            coverPathLow: PlaylistsPageProps.selected-playlist.coverPath,
            extension-icon: @image-url("../icons/song_default.svg"),
        };
    }
}
