import { PlaylistModel } from "../types/song_view.slint";
import { GridPageLayout } from "../common/grid_page_layout.slint";
import { Constants, Pages } from "../constants.slint";
import { ContextMenuCallbacks } from "../callbacks.slint";
import { AppProps } from "../props.slint";

export global PlaylistsPageProps {
    in-out property <[PlaylistModel]> playlists: Constants.testPlaylists;
    in-out property <PlaylistModel> selected-playlist;
}

export component PlaylistsPage inherits Rectangle {
    background: transparent;

    GridPageLayout {
        title: @tr("Playlists");
        total_items: PlaylistsPageProps.playlists.length;
        enable_context_menu: true;
        item_title(idx) => {
            PlaylistsPageProps.playlists[idx].title
        }
        item_cover(idx) => {
            PlaylistsPageProps.playlists[idx].coverPath
        }
        item_extension(idx) => {
            PlaylistsPageProps.playlists[idx].extension
        }
        item_extension_icon(idx) => {
            PlaylistsPageProps.playlists[idx].extension_icon
        }
        item_clicked(idx) => {
            PlaylistsPageProps.selected-playlist = PlaylistsPageProps.playlists[idx];
            AppProps.active_page = Pages.PlaylistContent;
        }
        get_context_menu_items(idx) => {
            ContextMenuCallbacks.get_playlist_menu_items([PlaylistsPageProps.playlists[idx]])
        }
        context_menu_action(idx, action_id) => {
            ContextMenuCallbacks.playlist_action([PlaylistsPageProps.playlists[idx]], action_id)
        }
    }
}
