import { PlaylistModel } from "../types/song_view.slint";
import { GridListView } from "../common/grid_list_view.slint";
import { Constants, Theme } from "../constants.slint";

export component PlaylistsPage inherits Rectangle {
    in property <[PlaylistModel]> playlists: Constants.testPlaylists;

    background: transparent;

    VerticalLayout {
        spacing: Theme.spacingXxl;
        alignment: start;

        text := Text {
            height: Theme.pageHeader + Theme.paddingLg;
            text: "Playlists";
            font-size: Theme.pageHeader;
            color: Theme.textPrimary;
        }

        GridListView {
            height: root.height - text.height - (Theme.spacingXxl + Theme.paddingLg);
            item-width: Theme.cardWidth;
            total-items: root.playlists.length;
            item-title(idx) => {
                root.playlists[idx].title
            }
            item-cover(idx) => {
                root.playlists[idx].coverPath
            }
        }
    }
}
