load("@rules_rust//cargo:defs.bzl", "cargo_build_script")
load("@rules_rust//rust:defs.bzl", "rust_library")

# gazelle:rust_cargo_lockfile Cargo.lock
# gazelle:rust_crates_prefix @crates//:
# gazelle:rust_mode generate_from_cargo

filegroup(
    name = "permissions",
    srcs = glob([
        "permissions/**/*",
    ]),
)

rust_library(
    name = "tauri-plugin-file-scanner",
    srcs = [
        "src/desktop.rs",
        "src/lib.rs",
        "src/mobile.rs",
    ],
    compile_data = [
        ":permissions",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":build_script",
        "//core/types",
        "//core/types/protos:songs_rs",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:tauri",
    ],
)

filegroup(
    name = "android_sources",
    srcs = glob(["android/**/*"]),
)

cargo_build_script(
    name = "build_script",
    srcs = ["build.rs"],
    build_script_env = select({
        "//tools:target_android": {
            "DEP_TAURI_ANDROID_LIBRARY_PATH": "$(execpath //tools:tauri_android_sources)/mobile/android",
        },
        "//conditions:default": {},
    }),
    crate_root = "build.rs",
    data = [
        ":android_sources",
    ] + select({
        "//tools:target_android": ["//tools:tauri_android_sources"],
        "//conditions:default": [],
    }),
    pkg_name = "tauri-plugin-file-scanner",
    visibility = ["//visibility:public"],
    deps = ["@crates//:tauri-plugin"],
)
