name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04-arm

    steps:


      - uses: actions/checkout@v4

      - uses: bazel-contrib/setup-bazel@0.16.0
        with:
          bazelisk-version: '1.22.0'
          bazelisk-cache: true
          disk-cache: true
          repository-cache: true

      - name: Install Dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: >
            nasm yasm autoconf automake libtool pkg-config make build-essential clang
            libasound2-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libfontconfig1-dev
          version: 1.0

      - name: Run Tests
        run: bazel test //:all
